/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive) / <alpha-value>)",
          foreground: "hsl(var(--destructive-foreground) / <alpha-value>)",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        // MajiSalama custom colors
        ms: {
          black: '#000000',
          dark: '#080808',
          'near-black': '#181818',
          'soft-black': '#1b1b1b',
          lime: '#E6FF2B',
          'light-lime': '#F4FF7A',
          yellow: '#EAFF03',
          'warm-black': '#1A1714',
          'warm-dark': '#0D0B09',
          amber: '#FF9F2B',
          orange: '#FF7A00',
          red: '#FF2B2B',
          green: '#C4FF00',
          cyan: '#00E5FF',
          white: '#FFFFFF',
          'soft-white': '#F4F4F4',
          'text-muted': '#555555',
          grey: '#7D7D7D',
          'dark-grey': '#333333',
          'mid-grey': '#9A9A9A',
          ice: '#A2E2FF',
          mint: '#D2FFCF',
          lavender: '#F4EAFF',
          peach: '#FFE8E5',
          pink: '#FF2B91',
          'cyan-bright': '#00F0FF',
          'water-blue': '#0055FF',
        }
      },
      fontFamily: {
        display: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        body: ['Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-xl': ['120px', { lineHeight: '0.9', letterSpacing: '-0.02em' }],
        'display-lg': ['80px', { lineHeight: '0.92', letterSpacing: '-0.02em' }],
        'display-md': ['60px', { lineHeight: '0.95', letterSpacing: '-0.01em' }],
        'display-sm': ['48px', { lineHeight: '1.0', letterSpacing: '-0.01em' }],
        'display-xs': ['36px', { lineHeight: '1.05', letterSpacing: '-0.01em' }],
        'hero-heading': ['90px', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        'stat-number': ['64px', { lineHeight: '1.0', letterSpacing: '-0.02em' }],
        'nav-link': ['48px', { lineHeight: '1.0', letterSpacing: '-0.01em' }],
        'footer-heading': ['80px', { lineHeight: '0.95', letterSpacing: '-0.02em' }],
        'heading-lg': ['28px', { lineHeight: '1.15' }],
        'heading-md': ['24px', { lineHeight: '1.2' }],
        'heading-sm': ['20px', { lineHeight: '1.25' }],
        'heading-xs': ['18px', { lineHeight: '1.3' }],
        'body-lg': ['18px', { lineHeight: '1.55' }],
        'body-md': ['16px', { lineHeight: '1.6' }],
        'body-sm': ['14px', { lineHeight: '1.55' }],
        'body-xs': ['12px', { lineHeight: '1.5' }],
        'label-lg': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em' }],
        'label-md': ['12px', { lineHeight: '1.4', letterSpacing: '0.08em' }],
        'label-sm': ['10px', { lineHeight: '1.4', letterSpacing: '0.1em' }],
      },
      spacing: {
        'section-xl': '160px',
        'section-lg': '120px',
        'section-md': '80px',
        'section-sm': '40px',
        'content-max': '1400px',
      },
      borderRadius: {
        xl: "calc(var(--radius) + 4px)",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xs: "calc(var(--radius) - 6px)",
      },
      boxShadow: {
        xs: "0 1px 2px 0 rgb(0 0 0 / 0.05)",
        glass: "0 8px 32px rgba(0,0,0,0.3)",
        alert: "0 4px 20px rgba(255,43,43,0.4)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "caret-blink": {
          "0%,70%,100%": { opacity: "1" },
          "20%,50%": { opacity: "0" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.4" },
        },
        "scroll-indicator": {
          "0%, 100%": { opacity: "0.5" },
          "50%": { opacity: "1" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "grid-pulse": {
          "0%, 100%": { opacity: "0.08" },
          "50%": { opacity: "0.2" },
        },
        "slide-in-right": {
          from: { transform: "translateX(400px)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        "slide-out-right": {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(400px)", opacity: "0" },
        },
        "border-glow": {
          "0%, 100%": { borderColor: "rgba(255,43,43,0.3)" },
          "50%": { borderColor: "rgba(255,43,43,0.6)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "caret-blink": "caret-blink 1.25s ease-out infinite",
        "pulse-dot": "pulse-dot 2s ease-in-out infinite",
        "scroll-indicator": "scroll-indicator 2s ease-in-out infinite",
        "float": "float 4s ease-in-out infinite",
        "grid-pulse": "grid-pulse 4s ease-in-out infinite",
        "slide-in-right": "slide-in-right 0.5s cubic-bezier(0.19, 1, 0.22, 1) forwards",
        "slide-out-right": "slide-out-right 0.4s cubic-bezier(0.55, 0, 1, 0.45) forwards",
        "border-glow": "border-glow 2s ease-in-out infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
